-- phpMyAdmin SQL Dump
-- version 5.1.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Dec 04, 2022 at 02:10 PM
-- Server version: 10.4.18-MariaDB
-- PHP Version: 8.0.3

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `blog_proz`
--

-- --------------------------------------------------------

--
-- Table structure for table `blogger`
--

CREATE TABLE `blogger` (
  `id` int(11) NOT NULL,
  `author` text NOT NULL,
  `publish` date NOT NULL,
  `title` text NOT NULL,
  `content` longtext NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `blogger`
--

INSERT INTO `blogger` (`id`, `author`, `publish`, `title`, `content`) VALUES
(1, 'Sean Kernan', '2021-01-13', 'Person Is Secretly Unhappy with Their Life', 'A mere 14% of people said they were very happy in a recent report. In fact, we are more unhappy than we’ve been in 50 years.\r\nYet many of you wouldn’t know it. Most people don’t walk around sulking. Friends are good at putting up an emotional front. We are good at buying the illusion. Then, when that friend’s behavior changes, we take it personally. We forget there were signs all along. It was never about us.\r\nUnderstand the subtle signs of unhappiness and you’ll deepen your empathy. You’ll better understand yourself. Above all, you’ll have better social relationships, which is tied to better health, happiness, and longevity\r\nA married couple I know was going through this difficult phase. The wife was complaining to us about her husband. He was sleeping all day. He’d come home and just stay in his bed for ridiculous stretches of time. He’d wake up, go to work, work very hard. Then he’d return home and shut down.\r\nUnderstandably, his spouse was very unhappy as he wasn’t giving her attention or helping at home. The couple had been fighting a lot in the time leading up to this. Fast forward, they got divorced, in no small part due to his behavior.'),
(2, 'Asmita Karanje', '2021-01-28', 'Winners Don’t Quit Is A Big Lie — They Do.', 'In today’s workout training, my trainer said while doing planks — it’s all about mind over matter, you can do it if you think you can do it.\r\nYou might have heard it a million times we need to push our limits each time. After all, quitting is a bad word right. No one wants to be a quitter, a loser.\r\nThey say, ‘most battles are first fought in the minds of the great warriors and then in the battleground.’ That’s true, you need to be mentally strong to execute anything in life. And it’s not just in workouts but even in other walks of life — you don’t quit your job because you had one bad day, you don’t walk out of a relationship because of one small argument and you certainly don’t give up on your dreams because someone said so.\r\nYou are smart and you don’t need anyone to tell you to push harder. What you need to know is that you don’t need to feel guilty if you quit.\r\nIt stayed with me for a long time — when I appeared for competitive exams, during job interviews, and even when I pursued my writing career. Sometimes though, I pushed myself too hard because I didn’t know when was the right time to quit. I stayed in an investment banking job far too long because I thought quitting that job would reflect poorly on me that I can’t handle stress or I am not able to manage the increasing workload.\r\nWhile I was in the bubble, I didn’t realize I don’t have to deal with stress. I don’t have to work for 14 hours every day. I deserve to have a life outside of work. The job with all its money wasn’t the right choice for me. When I left that job, I felt liberated — I was happy to be out of that toxic place. I didn’t have another role in hand when I put down my papers — but within two weeks I got an offer from another company and I am still working here — it was the best decision I made.'),
(3, 'Princess Lucia Bishop', '2021-02-04', 'How to master your time', 'Imagine you were a Jedi master called Bob (your parents, whilst skilled in the ways of the force weren’t the best at choosing names). The love of your life – Princess Lucia – is trapped in a burning building as you hurry to save her.\r\nYou might think of Lucia as the embodiment of your dreams, your aspirations – she is your most important thing.\r\n\r\nUnfortunately, before you can reach her an army of stormtroopers open fire. The incoming stream of lasers demand your attention – if you fail to dodge them, you’re dead. You might think of them as an urgent distraction from saving your princess.\r\nThe secret to mastering your time is to systematically focus on importance and suppress urgency. Humans are pre-wired to focus on things which demand an immediate response, like alerts on their phones – and to postpone things which are most important, like going to the gym. You need to reverse that, which goes against your brain and most of human society.\r\n\r\nLook at what you spend your day doing. Most of it, I’ll warrant, is not anything you chose – it’s what is being asked of you.'),
(4, 'Lidiya', '2021-02-11', 'How to be adaptive when things are changing very fast', 'If there’s one thing you need to be good at, even though you may not know it, it’s to be adaptive.\r\n\r\nAdaptiveness is necessity these days as the world is changing literally every minute. Trying to keep up, stay up to date, change yourself at the same time, and still have the time to enjoy life, is impossible. You’ll either end up depressed, physically and emotionally tired, stressed out, anxious, or without having reached any goal due to the number of goals you’re after and the many tasks on your to-do list.\r\n\r\nThe solution lies in learning how to be adaptive.\r\n\r\nOnce you do that, you’ll simply go with the flow, and easily get used to any new environment, life change, unexpected situation, bad news, or else, and still be productive and happy.\r\n\r\nNot being adaptive is quite obvious, because the consequences are always the same.\r\n\r\nYou experience any type of change, and because it’s something new, you need all your focus and energy to get used to it. Which means leaving behind all your business and personal projects.\r\n\r\nWhen uncertainty knocks on the door again (meaning, when you realize that anything in life is uncertain and you can never know what’s going to happen next), you not only get anxious, but neglect your health, can’t sleep at night, can’t concentrate on anything important and your work performance is poor.'),
(5, 'Steve QJ', '2021-02-19', 'Anti-Racism Is Becoming Troublingly Racist', 'You’re supposed to be patient when it takes them 17 minutes to tie their shoelaces. You’re supposed to applaud their migraine-inducing attempts to play the violin. You’re supposed to give your undivided attention as they tell stories that somehow lack a beginning, a middle, and an end.\r\nBut worst of all is when a child wants to “help” you with something. You know that accepting their help will quadruple the time, energy, and resources required to get anything done. You realise that it’d be far simpler to do the job yourself. You’re aware that they’ll get bored halfway through and give up. But what are you supposed to tell them? They’re so enthusiastic, so earnest, so eager to contribute. So you take a deep breath, grit your teeth into a smile, and watch them make a mess.\r\nIf you’ve been watching the trajectory of anti-racism over the past few years, you can probably relate. It’s become an exercise in patiently explaining things that should be painfully obvious. It’s an endless parade of clickbait headlines and performative outrage. It’s dominated by people who seem as if they want to help but are hopelessly confused about how to do so.'),
(6, 'Concoda', '2021-03-08', 'Cryptocurrencies Are About To Tear Our Society Apart', 'Right now, fortunes are being made in the crypto markets, but this keeps distracting us from recognizing the long-term effects of decentralization on modern-day society. Whether Bitcoin reaches $500,000, Ethereum becomes top dog, or another unknown successor takes the top spot, this does not matter when you realize the bigger picture. Satoshi Nakamoto’s whitepaper will start to transform the world in profound ways that we can’t truly comprehend. But what we can say is that it’s about to change a lot more than just the monetary system.\r\nIf you remember why Nakamoto created Bitcoin, it was a quiet protest against government tyranny, a people’s currency designed to eliminate state intrusion. Before blockchain existed, governments could ban any medium that enabled people to escape financial repression. In 1933, FDR passed Executive Order 6102 which banned citizens from hoarding gold, forcing them to turn it in. Previous attempts at digital currencies also failed. e-Gold was a disaster, and Liberty Reserve, which branded itself as a centralized digital currency system, collapsed after authorities shut it down.\r\nIf so, the manifestation of the decentralist-centralist divide in society will be an extremely slow process. It takes time for crises to develop to invoke significant change.\r\nYou can’t be shut down by the billionaire owner of Bitcoin. The creator of Bitcoin is a mystery — it could be Wonder Woman for all we know. You’re free to look into Bitcoin or not. You’re free to buy Bitcoin. You’re free to transact in Bitcoin.\r\nPeople get easily caught in the hype cycle of Bitcoin, or the anger in the fact they didn’t buy Bitcoin, and so they feel like they must throw stones at anybody who did.'),
(7, 'Kat Orekhova', '2021-03-23', 'Should You Leave a Big Company for a Startup?', 'if you’re reading this, the door is already open. Maybe you’ve been at a big tech company a few years and it’s not as exciting as it used to be. Maybe a founder reached out to you about an open role and you can’t get the idea out of your head.\r\nEither way, you’re considering joining a startup. You know that a young company would offer you new opportunities that you can’t get at your current job.\r\nEven though the prospect of joining a startup feels exciting, the decision to leave feels like a war between emotion and logic. You want to go for it but you’re still uncertain.\r\nIf you feel this way, you are not alone. While recruiting for Vareto, I’ve spoken to dozens of people in this exact situation. It doesn’t matter whether you’ve got two years of experience or twenty. It doesn’t matter whether you’re just starting your career or leading an organization. People have similar questions and concerns.\r\nThis post is a summary of those concerns. Only you can decide, but hopefully, this helps you frame that decision more clearly.\r\n\r\nMany people tell me that they’re waiting to make the jump. They want to become a Director, a VP, or reach some other milestone before joining a startup. But as you progress in your career, it actually becomes more difficult to leave. You’ll have larger projects and teams you’re responsible for, and you’ll be making even more money.'),
(8, 'L.C Bird', '2021-04-10', 'The Mountain More Deadly Than Everest', 'Mount Everest sure gets a lot of hype. Countless movies, documentaries, books have been made about it, and even a ride at Disney World has been named after it. And if you polled the average person on the street, most would say Everest when asked to name a mountain. But Everest, though it’s so well-known as a dangerous summit, is not the deadliest mountain in the world. It’s not even the second or third deadliest. The title of the deadliest mountain in the world goes to a close cousin of Everest, Annapurna I.\r\nLike Everest, Annapurna I is a peak in the Himalayas, in north-central Nepal, and one of four main summits in the Annapurna massif. Annapurna is one of 14 eight-thousand meter peaks across the globe, and the first “eight-thousander” successfully summited, a feat accomplished by French climbers in 1950.\r\n\r\nAlthough only the tenth tallest mountain peak in the world, Annapurna I is the deadliest when considering the ratio of summits to deaths. Of the 191 climbers who have summited the mountain, 63 have died, making the fatality rate 33%. Everest’s 4% fatality rate pales in comparison.\r\nPeople die on Annapurna for a number of reasons. Climbers have fallen from cliffs, fallen into crevasses, died in avalanches, and succumbed to heart attacks and high-altitude cerebral edema. In 2014, an unexpected storm killed 43 people and five climbers at the base camp died buried in snow in their tents.'),
(9, 'Matt Bruning', '2021-04-14', 'Sports vs. digital technologies — an exciting gameplay', 'Digitization is not only an overused buzzword but also a turbine that keeps the corporate world running. It changes our behavior, affects existing business processes, enables new, innovative management opportunities, and brings a customer closer to the center of attention. It all applies to the modern sports industry, too. A well-adjusted technology can reduce the gap between a spectator and a game, and provide players, both professional and amateur, with a motivational boost. However, the revolution doesn’t just happen by itself. Let’s get the ball rolling and check how to make sports both digital and unmatched.\r\n\r\nThe potential is huge but we’ll try to narrow it down to several, paramount points. The task is to explain how to use technologies in sport, making it even more exciting for the audience and orderly from the management point of view.\r\n\r\nFirst of all, technologies can help you keep your data neat by proper visualization, controlling sensors, and training documentation handled with ease.\r\nYou want to provide your players with enhanced training and higher competitiveness? Computer science can support sports experts and coaches in getting their teams to the top.\r\nUsing exhaustive statistics and assuring real-time information improves fans’ experience, making them up to date with their favorite team or athlete.\r\nThere’s something for amateurs, too. With the use of AI-based applications, they’re able to track their progress, update their skills, as well as connect with each other and compare to different athletes.'),
(10, 'Bill Fulton', '2021-04-21', 'Life On The Edge', 'I am on the edge. Not emotionally or psychologically — although this could be the case — but literally, physically, spatially, geographically. As I write this, I am sitting on the balcony of a hotel room in Miami Beach, overlooking the Atlantic Ocean. Behind me is the whole State of Florida and, indeed, the entire North American continent. In front of me: the boardwalk, a narrow beach, and then a lot of water — and not much else between here and Mauritania, a distance of more than 4,400 miles.\r\nThis is what urban designers call an “edge” — a transition between, you might say, something and nothing. Urban designers think constantly about things like edges, nodes, paths — anything, as the brilliant urban designer Kevin Lynch showed us in his classic book The Image of the City, that makes a city “legible,” easier for people to navigate and understand.\r\nMost people don’t think much about urban design as a field of study, but they do respond to edges like you wouldn’t believe. In the big picture, nearly 40% of the people in the U.S. — more than 130 million people — live in counties that hug the coasts. But even more compelling is the close-up: tall buildings and dense districts hugging an edge in order to be near something natural-seeming, something different from the city around them. What else do Central Park West, the Texas Medical Center, and Miami Beach have in common? They are all densely built-up edges, high-rises pressing up against nature: the great, green expanse of Central Park, the parklike setting of Rice University, the boundless Atlantic Ocean.'),
(11, 'Alyssa Atkinson', '2021-04-22', 'I Run Almost Every Single Day and You Should Too', 'Up until I entered middle school, I never considered myself to be a runner. This was mostly because I had always been focused on another sport.\r\nI started playing basketball in first grade. The older I got, the more serious I became. I used to dribble the ball on the hard tile in my kitchen for an hour almost every single day.\r\nRunning was just a small part of the sport of basketball for me, and nothing more. That is, until I joined the cross-country team in eighth grade.\r\nI didn’t want to go to the first mandatory cross-country practice on that hot summer day in August, but my parents told me I had to play a fall sport. My options were either soccer or cross-country, and I was terrible at soccer, so I decided to join the cross-country team.\r\nIt became quickly apparent after my first cross-country race that I had a lot of natural talent, and that initial success kept me in the sport all the way through college. It has been over a year since I graduated college, and I continue to run almost every single day today. I do it for the pure joy that it brings me, and for the health benefits that running provides me with.\r\nThe following are three science-backed reasons you also should consider running often. In sharing them, I hope to inspire you to give running a chance.\r\nIf you are looking for mental clarity, running can help you find it. You might have noticed a feeling of inspiration wash over you while out on a run before, and there is actually some science to support the mental stimulation you experience during exercise.\r\nWhenever I struggle with a stressful work situation, a simple run always makes me feel better, even if just for a little while. I can practically feel the stress leaving my body every time I exhale. By the time I complete my run, I can’t help but smile. This is yet another reason you should consider picking up the sport of running.\r\nOver the span of the 10+ years I have been running, the sport has provided me with a variety of benefits. Running began as a way to stay in shape for basketball, but it eventually turned into my stress reliever, mental booster, and true source of joy.\r\nGive running a chance, stay consistent with it, and you never know what opportunities it will provide you with. If nothing else, it will help you feel healthier and happier overall.'),
(12, 'Umair Haque', '2021-04-29', 'This is Why the World is Facing a Covid Apocalypse', 'By now, you’re beginning to read stories of Covid apocalypse in countries like India. Maybe South Africa. Perhaps Indonesia. Then will come Pakistan, Peru, Argentina. It’s just beginning. Covid apocalypse is on the way to becoming Covid holocaust. Don’t believe me? Good. Let’s dig in, together.\r\nWhat do I mean by “Covid holocaust”? Am I exaggerating, like every white dude on planet earth is going to tell me, smugly, rolling their eyes? Let’s do a little simple math together, Chad. The world’s population is 8 billion people, give or take. Covid’s mortality rate — this is just the current variants — is about 2%. Let’s assume half the world eventually gets infected — so far, somewhere between 5 and 10% of the world has.\r\nHow many deaths is that? 160,000,000. Holocaust enough for you? That’s too much, to be sure. Let’s assume just half the world gets infected, at a mortality rate of 1%. A total number of deaths? Forty million.\r\nThat is modern history’s greatest holocaust, by a very long way.\r\nAt this juncture — and now we’re going to get to what this post is really about — some of you are going to object, angrily: “But vaccines! We have vaccines! You’re being ridiculous!” If only I were. “We” don’t have vaccines. The rich world has them. That’s 15% of people in the world. The other 80%? Of humanity? They barely have any vaccines, and they’re not getting them nearly fast enough to prevent the kind of tragedy that’s unfolding in places like India.\r\nWhy is that? Because the world’s approach to vaccination has failed catastrophically. And it is producing the Covid apocalypse, which is sure to become the Covid holocaust.\r\nPoor countries are vaccinating people at a snail’s pace. India’s vaccinating two million people a day. Sound like a lot? At that rate, it takes almost two years for the country to be half-vaccinated, with one dose. And four years for it to be fully vaccinated. Suddenly, the Covid holocaust I’ve outlined above doesn’t seem so far-fetched, does it? How many deaths is that, in a country of a billion people plus? Nobody can say, for sure. The upper limit is twenty million.\r\n');

-- --------------------------------------------------------

--
-- Table structure for table `contactme`
--

CREATE TABLE `contactme` (
  `name` varchar(50) NOT NULL,
  `email` varchar(25) NOT NULL,
  `contact` bigint(20) NOT NULL,
  `suggest` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `contactme`
--

INSERT INTO `contactme` (`name`, `email`, `contact`, `suggest`) VALUES
('Devendra', 'devd12@gmail.com', 1883746321, 'My account is locked plz help me unlock it and also my post has been deleted. '),
('Rahul', 'rahulraj65@gmail.com', 9947354546, 'Hey i am excited and thank you for creating such a wonderful platform to share our thoughts and story to open world. '),
('Sherman', 'sherman@gmail.com', 7347574852, 'Hey, my account is locked help me to unlock it.'),
('sdsdsd', 'sdsds', 0, 'sfsfsfsfsfsfsf');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `blogger`
--
ALTER TABLE `blogger`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `blogger`
--
ALTER TABLE `blogger`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=14;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
